Adjust Flows app to new Project model.
weni-ai/rapidpro-apps pull request #239
Opened 2023-05-30 12:11 UTC by lucaslinhares

Adjust Flows app according to new Project model.

2023-06-20 19:34 UTC, elitonzky requested changes
Need a little change

2023-06-22 21:15 UTC, lucaslinhares commented on weni/internal/flows/tests.py
>          # print(Org.objects.all())
Done

2023-06-22 21:39 UTC, AlisoSouza approved these changes

2023-06-22 21:51 UTC, elitonzky approved these changes

2023-06-22 21:53 UTC, merged